### ISSUE TITLE
Issues with coins < 1

### ISSUE THREAD

**Issue by pgastinger** [alfonsrv/crypto-tracker#1]
Hi, 

Nice tracker! I am running it in a Docker swarm with Traefik and Letsencrypt and I ran into following problem:
```
  File "/app/crypto/templatetags/crypto_extras.py", line 37, in cryptoformat
    float_format = int(str(value).partition('-')[2]) + 100
ValueError: invalid literal for int() with base 10: ''
```
I do not know why you are using "-" here, e.g. if the coin value is 0.04321, then you should use a ".":
```
        float_format = int(str(value).partition('.')[2]) + 100
```
At least this solved the problem for me. 

regards, 
Peter

**Comment by alfonsrv** [comment]
Probably a typo; pushed a commit to fix it.

Hope the tracker is fun to use.

Thanks for the pointer! Best,
Alfons
